### ISSUE TITLE
autotools on Ubuntu 14.04

### ISSUE THREAD

**Issue by thomasLeMeur** [CICM/HoaLibrary-PD#2]
When I use the command ./configure, I have this error message : 
./configure: line 2317: syntax error near unexpected token `am__api_version='1.14''
./configure: line 2317:`am__api_version='1.14''

If I change this line into a commentary line, it works but maybe it implies some building defaults.
Thanks

**Comment by pierreguillot** [comment]
The compilation is based on cmake now.

**Comment by meschi** [comment]
It would be nice if you could merge the refactored branch back into the master.
