### ISSUE TITLE
Export audio as an ambisonics compatible file.

### ISSUE THREAD

**Issue by aristizabal95** [CICM/HoaLibrary-PD#6]
Hello, I'm checking out your PD Library and looks awesome! I was wondering if there is any way an user can export the encoded ambisonics audio into a compatible file.

Right now, I'm interested on converting some mono audio into a .ambix file, and have looked everywhere for a library that would do this. Is it possible with this library?? Thanks

**Comment by pierreguillot** [comment]
Hi,
I'm working on a better compatibility of the library right now but I don't think we'll ever manage the creation of the ambisonics files. What you can do with the library is to encode a mono source into the spherical harmonics domain and to save with Pd the ambisonics channels but the library doesn't manage the file format and the metadata.

**Comment by aristizabal95** [comment]
Thanks for answering, it's a shame there is no way to export the encoded audio directly from pd, I will try exporting each individual channel from the matrix and building the file myself. Thanks again!
